// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.0--rc1
// source: morpho/models/getAPR.proto

package morpho

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAPRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	PoolAddress  string `protobuf:"bytes,2,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	ChainId      int64  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (x *GetAPRRequest) Reset() {
	*x = GetAPRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_morpho_models_getAPR_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAPRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPRRequest) ProtoMessage() {}

func (x *GetAPRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_morpho_models_getAPR_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPRRequest.ProtoReflect.Descriptor instead.
func (*GetAPRRequest) Descriptor() ([]byte, []int) {
	return file_morpho_models_getAPR_proto_rawDescGZIP(), []int{0}
}

func (x *GetAPRRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetAPRRequest) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *GetAPRRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetAPRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplyAPR string `protobuf:"bytes,1,opt,name=supplyAPR,proto3" json:"supplyAPR,omitempty"`
	BorrowAPR string `protobuf:"bytes,2,opt,name=borrowAPR,proto3" json:"borrowAPR,omitempty"`
}

func (x *GetAPRResponse) Reset() {
	*x = GetAPRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_morpho_models_getAPR_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAPRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPRResponse) ProtoMessage() {}

func (x *GetAPRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_morpho_models_getAPR_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPRResponse.ProtoReflect.Descriptor instead.
func (*GetAPRResponse) Descriptor() ([]byte, []int) {
	return file_morpho_models_getAPR_proto_rawDescGZIP(), []int{1}
}

func (x *GetAPRResponse) GetSupplyAPR() string {
	if x != nil {
		return x.SupplyAPR
	}
	return ""
}

func (x *GetAPRResponse) GetBorrowAPR() string {
	if x != nil {
		return x.BorrowAPR
	}
	return ""
}

var File_morpho_models_getAPR_proto protoreflect.FileDescriptor

var file_morpho_models_getAPR_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x6f, 0x72, 0x70, 0x68, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x67, 0x65, 0x74, 0x41, 0x50, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f,
	0x72, 0x70, 0x68, 0x6f, 0x22, 0x6f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x50, 0x52, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x6f,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x50, 0x52, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x41, 0x50, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x41, 0x50, 0x52, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x41,
	0x50, 0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x41, 0x50, 0x52, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x72,
	0x70, 0x68, 0x6f, 0x3b, 0x6d, 0x6f, 0x72, 0x70, 0x68, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_morpho_models_getAPR_proto_rawDescOnce sync.Once
	file_morpho_models_getAPR_proto_rawDescData = file_morpho_models_getAPR_proto_rawDesc
)

func file_morpho_models_getAPR_proto_rawDescGZIP() []byte {
	file_morpho_models_getAPR_proto_rawDescOnce.Do(func() {
		file_morpho_models_getAPR_proto_rawDescData = protoimpl.X.CompressGZIP(file_morpho_models_getAPR_proto_rawDescData)
	})
	return file_morpho_models_getAPR_proto_rawDescData
}

var file_morpho_models_getAPR_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_morpho_models_getAPR_proto_goTypes = []interface{}{
	(*GetAPRRequest)(nil),  // 0: morpho.GetAPRRequest
	(*GetAPRResponse)(nil), // 1: morpho.GetAPRResponse
}
var file_morpho_models_getAPR_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_morpho_models_getAPR_proto_init() }
func file_morpho_models_getAPR_proto_init() {
	if File_morpho_models_getAPR_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_morpho_models_getAPR_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAPRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_morpho_models_getAPR_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAPRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_morpho_models_getAPR_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_morpho_models_getAPR_proto_goTypes,
		DependencyIndexes: file_morpho_models_getAPR_proto_depIdxs,
		MessageInfos:      file_morpho_models_getAPR_proto_msgTypes,
	}.Build()
	File_morpho_models_getAPR_proto = out.File
	file_morpho_models_getAPR_proto_rawDesc = nil
	file_morpho_models_getAPR_proto_goTypes = nil
	file_morpho_models_getAPR_proto_depIdxs = nil
}
