// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.0--rc1
// source: hyperlend/service.proto

package hyperlend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HyperLendService_SupplyERC20_FullMethodName        = "/hyperlend.HyperLendService/SupplyERC20"
	HyperLendService_WithdrawERC20_FullMethodName      = "/hyperlend.HyperLendService/WithdrawERC20"
	HyperLendService_GetAPR_FullMethodName             = "/hyperlend.HyperLendService/GetAPR"
	HyperLendService_GetLendingPool_FullMethodName     = "/hyperlend.HyperLendService/GetLendingPool"
	HyperLendService_GetSuppliedBalance_FullMethodName = "/hyperlend.HyperLendService/GetSuppliedBalance"
)

// HyperLendServiceClient is the client API for HyperLendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperLendServiceClient interface {
	SupplyERC20(ctx context.Context, in *SupplyERC20Request, opts ...grpc.CallOption) (*SupplyERC20Response, error)
	WithdrawERC20(ctx context.Context, in *WithdrawERC20Request, opts ...grpc.CallOption) (*WithdrawERC20Response, error)
	GetAPR(ctx context.Context, in *GetAPRRequest, opts ...grpc.CallOption) (*GetAPRResponse, error)
	GetLendingPool(ctx context.Context, in *GetLendingPoolRequest, opts ...grpc.CallOption) (*GetLendingPoolResponse, error)
	GetSuppliedBalance(ctx context.Context, in *SuppliedBalanceRequest, opts ...grpc.CallOption) (*SuppliedBalanceResponse, error)
}

type hyperLendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperLendServiceClient(cc grpc.ClientConnInterface) HyperLendServiceClient {
	return &hyperLendServiceClient{cc}
}

func (c *hyperLendServiceClient) SupplyERC20(ctx context.Context, in *SupplyERC20Request, opts ...grpc.CallOption) (*SupplyERC20Response, error) {
	out := new(SupplyERC20Response)
	err := c.cc.Invoke(ctx, HyperLendService_SupplyERC20_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperLendServiceClient) WithdrawERC20(ctx context.Context, in *WithdrawERC20Request, opts ...grpc.CallOption) (*WithdrawERC20Response, error) {
	out := new(WithdrawERC20Response)
	err := c.cc.Invoke(ctx, HyperLendService_WithdrawERC20_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperLendServiceClient) GetAPR(ctx context.Context, in *GetAPRRequest, opts ...grpc.CallOption) (*GetAPRResponse, error) {
	out := new(GetAPRResponse)
	err := c.cc.Invoke(ctx, HyperLendService_GetAPR_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperLendServiceClient) GetLendingPool(ctx context.Context, in *GetLendingPoolRequest, opts ...grpc.CallOption) (*GetLendingPoolResponse, error) {
	out := new(GetLendingPoolResponse)
	err := c.cc.Invoke(ctx, HyperLendService_GetLendingPool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperLendServiceClient) GetSuppliedBalance(ctx context.Context, in *SuppliedBalanceRequest, opts ...grpc.CallOption) (*SuppliedBalanceResponse, error) {
	out := new(SuppliedBalanceResponse)
	err := c.cc.Invoke(ctx, HyperLendService_GetSuppliedBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperLendServiceServer is the server API for HyperLendService service.
// All implementations should embed UnimplementedHyperLendServiceServer
// for forward compatibility
type HyperLendServiceServer interface {
	SupplyERC20(context.Context, *SupplyERC20Request) (*SupplyERC20Response, error)
	WithdrawERC20(context.Context, *WithdrawERC20Request) (*WithdrawERC20Response, error)
	GetAPR(context.Context, *GetAPRRequest) (*GetAPRResponse, error)
	GetLendingPool(context.Context, *GetLendingPoolRequest) (*GetLendingPoolResponse, error)
	GetSuppliedBalance(context.Context, *SuppliedBalanceRequest) (*SuppliedBalanceResponse, error)
}

// UnimplementedHyperLendServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHyperLendServiceServer struct {
}

func (UnimplementedHyperLendServiceServer) SupplyERC20(context.Context, *SupplyERC20Request) (*SupplyERC20Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyERC20 not implemented")
}
func (UnimplementedHyperLendServiceServer) WithdrawERC20(context.Context, *WithdrawERC20Request) (*WithdrawERC20Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawERC20 not implemented")
}
func (UnimplementedHyperLendServiceServer) GetAPR(context.Context, *GetAPRRequest) (*GetAPRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPR not implemented")
}
func (UnimplementedHyperLendServiceServer) GetLendingPool(context.Context, *GetLendingPoolRequest) (*GetLendingPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLendingPool not implemented")
}
func (UnimplementedHyperLendServiceServer) GetSuppliedBalance(context.Context, *SuppliedBalanceRequest) (*SuppliedBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuppliedBalance not implemented")
}

// UnsafeHyperLendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperLendServiceServer will
// result in compilation errors.
type UnsafeHyperLendServiceServer interface {
	mustEmbedUnimplementedHyperLendServiceServer()
}

func RegisterHyperLendServiceServer(s grpc.ServiceRegistrar, srv HyperLendServiceServer) {
	s.RegisterService(&HyperLendService_ServiceDesc, srv)
}

func _HyperLendService_SupplyERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplyERC20Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperLendServiceServer).SupplyERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperLendService_SupplyERC20_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperLendServiceServer).SupplyERC20(ctx, req.(*SupplyERC20Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperLendService_WithdrawERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawERC20Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperLendServiceServer).WithdrawERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperLendService_WithdrawERC20_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperLendServiceServer).WithdrawERC20(ctx, req.(*WithdrawERC20Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperLendService_GetAPR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperLendServiceServer).GetAPR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperLendService_GetAPR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperLendServiceServer).GetAPR(ctx, req.(*GetAPRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperLendService_GetLendingPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLendingPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperLendServiceServer).GetLendingPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperLendService_GetLendingPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperLendServiceServer).GetLendingPool(ctx, req.(*GetLendingPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperLendService_GetSuppliedBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuppliedBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperLendServiceServer).GetSuppliedBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperLendService_GetSuppliedBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperLendServiceServer).GetSuppliedBalance(ctx, req.(*SuppliedBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HyperLendService_ServiceDesc is the grpc.ServiceDesc for HyperLendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyperLendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperlend.HyperLendService",
	HandlerType: (*HyperLendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupplyERC20",
			Handler:    _HyperLendService_SupplyERC20_Handler,
		},
		{
			MethodName: "WithdrawERC20",
			Handler:    _HyperLendService_WithdrawERC20_Handler,
		},
		{
			MethodName: "GetAPR",
			Handler:    _HyperLendService_GetAPR_Handler,
		},
		{
			MethodName: "GetLendingPool",
			Handler:    _HyperLendService_GetLendingPool_Handler,
		},
		{
			MethodName: "GetSuppliedBalance",
			Handler:    _HyperLendService_GetSuppliedBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperlend/service.proto",
}
