// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.0--rc1
// source: hyperlend/models/supplyERC20.proto

package hyperlend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplyERC20Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress         string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	OrchestratorAddress string `protobuf:"bytes,2,opt,name=orchestratorAddress,proto3" json:"orchestratorAddress,omitempty"`
	StrategyId          string `protobuf:"bytes,3,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	PoolAddress         string `protobuf:"bytes,4,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	Amount              string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetAddress        string `protobuf:"bytes,6,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
}

func (x *SupplyERC20Request) Reset() {
	*x = SupplyERC20Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hyperlend_models_supplyERC20_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyERC20Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyERC20Request) ProtoMessage() {}

func (x *SupplyERC20Request) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlend_models_supplyERC20_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyERC20Request.ProtoReflect.Descriptor instead.
func (*SupplyERC20Request) Descriptor() ([]byte, []int) {
	return file_hyperlend_models_supplyERC20_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyERC20Request) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *SupplyERC20Request) GetOrchestratorAddress() string {
	if x != nil {
		return x.OrchestratorAddress
	}
	return ""
}

func (x *SupplyERC20Request) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *SupplyERC20Request) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *SupplyERC20Request) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SupplyERC20Request) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

type SupplyERC20Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId int64  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TxHash  string `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Amount  string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SupplyERC20Response) Reset() {
	*x = SupplyERC20Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hyperlend_models_supplyERC20_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyERC20Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyERC20Response) ProtoMessage() {}

func (x *SupplyERC20Response) ProtoReflect() protoreflect.Message {
	mi := &file_hyperlend_models_supplyERC20_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyERC20Response.ProtoReflect.Descriptor instead.
func (*SupplyERC20Response) Descriptor() ([]byte, []int) {
	return file_hyperlend_models_supplyERC20_proto_rawDescGZIP(), []int{1}
}

func (x *SupplyERC20Response) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SupplyERC20Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SupplyERC20Response) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_hyperlend_models_supplyERC20_proto protoreflect.FileDescriptor

var file_hyperlend_models_supplyERC20_proto_rawDesc = []byte{
	0x0a, 0x22, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x52, 0x43, 0x32, 0x30, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x22,
	0xe6, 0x01, 0x0a, 0x12, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x52, 0x43, 0x32, 0x30, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f,
	0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5f, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x45, 0x52, 0x43, 0x32, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x62, 0x2f,
	0x67, 0x6f, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x3b, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x6c, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hyperlend_models_supplyERC20_proto_rawDescOnce sync.Once
	file_hyperlend_models_supplyERC20_proto_rawDescData = file_hyperlend_models_supplyERC20_proto_rawDesc
)

func file_hyperlend_models_supplyERC20_proto_rawDescGZIP() []byte {
	file_hyperlend_models_supplyERC20_proto_rawDescOnce.Do(func() {
		file_hyperlend_models_supplyERC20_proto_rawDescData = protoimpl.X.CompressGZIP(file_hyperlend_models_supplyERC20_proto_rawDescData)
	})
	return file_hyperlend_models_supplyERC20_proto_rawDescData
}

var file_hyperlend_models_supplyERC20_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hyperlend_models_supplyERC20_proto_goTypes = []interface{}{
	(*SupplyERC20Request)(nil),  // 0: hyperlend.SupplyERC20Request
	(*SupplyERC20Response)(nil), // 1: hyperlend.SupplyERC20Response
}
var file_hyperlend_models_supplyERC20_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hyperlend_models_supplyERC20_proto_init() }
func file_hyperlend_models_supplyERC20_proto_init() {
	if File_hyperlend_models_supplyERC20_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hyperlend_models_supplyERC20_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyERC20Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hyperlend_models_supplyERC20_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyERC20Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hyperlend_models_supplyERC20_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hyperlend_models_supplyERC20_proto_goTypes,
		DependencyIndexes: file_hyperlend_models_supplyERC20_proto_depIdxs,
		MessageInfos:      file_hyperlend_models_supplyERC20_proto_msgTypes,
	}.Build()
	File_hyperlend_models_supplyERC20_proto = out.File
	file_hyperlend_models_supplyERC20_proto_rawDesc = nil
	file_hyperlend_models_supplyERC20_proto_goTypes = nil
	file_hyperlend_models_supplyERC20_proto_depIdxs = nil
}
