// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.0--rc1
// source: biconomy/models/usePermission.proto

package biconomy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrchestratorAddress string         `protobuf:"bytes,1,opt,name=orchestratorAddress,proto3" json:"orchestratorAddress,omitempty"`
	StrategyId          string         `protobuf:"bytes,2,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	TxData              []*Instruction `protobuf:"bytes,3,rep,name=txData,proto3" json:"txData,omitempty"`
	FeeToken            string         `protobuf:"bytes,4,opt,name=feeToken,proto3" json:"feeToken,omitempty"`
	FeeChainId          int64          `protobuf:"varint,5,opt,name=feeChainId,proto3" json:"feeChainId,omitempty"`
}

func (x *UsePermissionRequest) Reset() {
	*x = UsePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconomy_models_usePermission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePermissionRequest) ProtoMessage() {}

func (x *UsePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biconomy_models_usePermission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePermissionRequest.ProtoReflect.Descriptor instead.
func (*UsePermissionRequest) Descriptor() ([]byte, []int) {
	return file_biconomy_models_usePermission_proto_rawDescGZIP(), []int{0}
}

func (x *UsePermissionRequest) GetOrchestratorAddress() string {
	if x != nil {
		return x.OrchestratorAddress
	}
	return ""
}

func (x *UsePermissionRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *UsePermissionRequest) GetTxData() []*Instruction {
	if x != nil {
		return x.TxData
	}
	return nil
}

func (x *UsePermissionRequest) GetFeeToken() string {
	if x != nil {
		return x.FeeToken
	}
	return ""
}

func (x *UsePermissionRequest) GetFeeChainId() int64 {
	if x != nil {
		return x.FeeChainId
	}
	return 0
}

type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To               string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Value            string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Data             string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	FunctionSelector string `protobuf:"bytes,4,opt,name=functionSelector,proto3" json:"functionSelector,omitempty"`
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconomy_models_usePermission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_biconomy_models_usePermission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_biconomy_models_usePermission_proto_rawDescGZIP(), []int{1}
}

func (x *Call) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Call) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Call) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Call) GetFunctionSelector() string {
	if x != nil {
		return x.FunctionSelector
	}
	return ""
}

type Instruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId int64   `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Calls   []*Call `protobuf:"bytes,2,rep,name=calls,proto3" json:"calls,omitempty"`
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconomy_models_usePermission_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_biconomy_models_usePermission_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_biconomy_models_usePermission_proto_rawDescGZIP(), []int{2}
}

func (x *Instruction) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Instruction) GetCalls() []*Call {
	if x != nil {
		return x.Calls
	}
	return nil
}

type UsePermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId int64  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TxHash  string `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
}

func (x *UsePermissionResponse) Reset() {
	*x = UsePermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconomy_models_usePermission_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePermissionResponse) ProtoMessage() {}

func (x *UsePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biconomy_models_usePermission_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePermissionResponse.ProtoReflect.Descriptor instead.
func (*UsePermissionResponse) Descriptor() ([]byte, []int) {
	return file_biconomy_models_usePermission_proto_rawDescGZIP(), []int{3}
}

func (x *UsePermissionResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *UsePermissionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_biconomy_models_usePermission_proto protoreflect.FileDescriptor

var file_biconomy_models_usePermission_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x22,
	0xd3, 0x01, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x78,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x65, 0x65, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x65, 0x65, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05,
	0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x63, 0x61, 0x6c,
	0x6c, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x42, 0x19, 0x5a,
	0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x3b,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconomy_models_usePermission_proto_rawDescOnce sync.Once
	file_biconomy_models_usePermission_proto_rawDescData = file_biconomy_models_usePermission_proto_rawDesc
)

func file_biconomy_models_usePermission_proto_rawDescGZIP() []byte {
	file_biconomy_models_usePermission_proto_rawDescOnce.Do(func() {
		file_biconomy_models_usePermission_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconomy_models_usePermission_proto_rawDescData)
	})
	return file_biconomy_models_usePermission_proto_rawDescData
}

var file_biconomy_models_usePermission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_biconomy_models_usePermission_proto_goTypes = []interface{}{
	(*UsePermissionRequest)(nil),  // 0: biconomy.UsePermissionRequest
	(*Call)(nil),                  // 1: biconomy.Call
	(*Instruction)(nil),           // 2: biconomy.Instruction
	(*UsePermissionResponse)(nil), // 3: biconomy.UsePermissionResponse
}
var file_biconomy_models_usePermission_proto_depIdxs = []int32{
	2, // 0: biconomy.UsePermissionRequest.txData:type_name -> biconomy.Instruction
	1, // 1: biconomy.Instruction.calls:type_name -> biconomy.Call
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biconomy_models_usePermission_proto_init() }
func file_biconomy_models_usePermission_proto_init() {
	if File_biconomy_models_usePermission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconomy_models_usePermission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconomy_models_usePermission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconomy_models_usePermission_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconomy_models_usePermission_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconomy_models_usePermission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconomy_models_usePermission_proto_goTypes,
		DependencyIndexes: file_biconomy_models_usePermission_proto_depIdxs,
		MessageInfos:      file_biconomy_models_usePermission_proto_msgTypes,
	}.Build()
	File_biconomy_models_usePermission_proto = out.File
	file_biconomy_models_usePermission_proto_rawDesc = nil
	file_biconomy_models_usePermission_proto_goTypes = nil
	file_biconomy_models_usePermission_proto_depIdxs = nil
}
