// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: protocol/service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { GetInfoRequest, GetInfoResponse } from "./models/protocol";

export const protobufPackage = "protocol";

export type ProtocolServiceService = typeof ProtocolServiceService;
export const ProtocolServiceService = {
  getInfo: {
    path: "/protocol.ProtocolService/GetInfo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInfoRequest): Buffer => Buffer.from(GetInfoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetInfoRequest => GetInfoRequest.decode(value),
    responseSerialize: (value: GetInfoResponse): Buffer => Buffer.from(GetInfoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetInfoResponse => GetInfoResponse.decode(value),
  },
} as const;

export interface ProtocolServiceServer extends UntypedServiceImplementation {
  getInfo: handleUnaryCall<GetInfoRequest, GetInfoResponse>;
}

export interface ProtocolServiceClient extends Client {
  getInfo(
    request: GetInfoRequest,
    callback: (error: ServiceError | null, response: GetInfoResponse) => void,
  ): ClientUnaryCall;
  getInfo(
    request: GetInfoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetInfoResponse) => void,
  ): ClientUnaryCall;
  getInfo(
    request: GetInfoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetInfoResponse) => void,
  ): ClientUnaryCall;
}

export const ProtocolServiceClient = makeGenericClientConstructor(
  ProtocolServiceService,
  "protocol.ProtocolService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ProtocolServiceClient;
  service: typeof ProtocolServiceService;
  serviceName: string;
};
