// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: protocol/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { GetInfoRequest, GetInfoResponse } from "./models/protocol";

export const protobufPackage = "protocol";

export const PROTOCOL_PACKAGE_NAME = "protocol";

export interface ProtocolServiceClient {
  getInfo(request: GetInfoRequest): Observable<GetInfoResponse>;
}

export interface ProtocolServiceController {
  getInfo(request: GetInfoRequest): Promise<GetInfoResponse> | Observable<GetInfoResponse> | GetInfoResponse;
}

export function ProtocolServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getInfo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProtocolService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProtocolService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROTOCOL_SERVICE_NAME = "ProtocolService";
