// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: aave/models/supplyERC20.proto

/* eslint-disable */

export const protobufPackage = "aave";

export interface SupplyERC20Request {
  userAddress: string;
  orchestratorAddress: string;
  strategyId: string;
  poolAddress: string;
  amount: string;
  assetAddress: string;
}

export interface SupplyERC20Response {
  chainId: number;
  txHash: string;
  amount: string;
}

export const AAVE_PACKAGE_NAME = "aave";
