// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: user/models/sign_in.proto

/* eslint-disable */

export const protobufPackage = "user";

export interface SignInRequest {
  message: string;
  signature: string;
}

export interface SignInResponseData {
  token: string;
}

export interface SignInResponse {
  code: number;
  msg: string;
  data: SignInResponseData | undefined;
}

export const USER_PACKAGE_NAME = "user";
