// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: price/models/price.proto

/* eslint-disable */

export const protobufPackage = "price";

export interface PriceRequest {
  source: string;
  token: string;
}

export interface PriceResponseData {
  price: number;
}

export interface PriceResponse {
  code: number;
  msg: string;
  data: PriceResponseData | undefined;
}

export const PRICE_PACKAGE_NAME = "price";
