// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: price/service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { PriceRequest, PriceResponse } from "./models/price";

export const protobufPackage = "price";

export type PriceServiceService = typeof PriceServiceService;
export const PriceServiceService = {
  getPrice: {
    path: "/price.PriceService/GetPrice",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PriceRequest): Buffer => Buffer.from(PriceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PriceRequest => PriceRequest.decode(value),
    responseSerialize: (value: PriceResponse): Buffer => Buffer.from(PriceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PriceResponse => PriceResponse.decode(value),
  },
} as const;

export interface PriceServiceServer extends UntypedServiceImplementation {
  getPrice: handleUnaryCall<PriceRequest, PriceResponse>;
}

export interface PriceServiceClient extends Client {
  getPrice(
    request: PriceRequest,
    callback: (error: ServiceError | null, response: PriceResponse) => void,
  ): ClientUnaryCall;
  getPrice(
    request: PriceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PriceResponse) => void,
  ): ClientUnaryCall;
  getPrice(
    request: PriceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PriceResponse) => void,
  ): ClientUnaryCall;
}

export const PriceServiceClient = makeGenericClientConstructor(
  PriceServiceService,
  "price.PriceService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PriceServiceClient;
  service: typeof PriceServiceService;
  serviceName: string;
};
