// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: price/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { PriceRequest, PriceResponse } from "./models/price";

export const protobufPackage = "price";

export const PRICE_PACKAGE_NAME = "price";

export interface PriceServiceClient {
  getPrice(request: PriceRequest): Observable<PriceResponse>;
}

export interface PriceServiceController {
  getPrice(request: PriceRequest): Promise<PriceResponse> | Observable<PriceResponse> | PriceResponse;
}

export function PriceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPrice"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PriceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PriceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRICE_SERVICE_NAME = "PriceService";
