// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.0--rc1
// source: hypurrfi/service.proto

package hypurrfi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HypurrfiService_SupplyERC20_FullMethodName        = "/hypurrfi.HypurrfiService/SupplyERC20"
	HypurrfiService_WithdrawERC20_FullMethodName      = "/hypurrfi.HypurrfiService/WithdrawERC20"
	HypurrfiService_GetAPR_FullMethodName             = "/hypurrfi.HypurrfiService/GetAPR"
	HypurrfiService_GetLendingPool_FullMethodName     = "/hypurrfi.HypurrfiService/GetLendingPool"
	HypurrfiService_GetSuppliedBalance_FullMethodName = "/hypurrfi.HypurrfiService/GetSuppliedBalance"
)

// HypurrfiServiceClient is the client API for HypurrfiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypurrfiServiceClient interface {
	SupplyERC20(ctx context.Context, in *SupplyERC20Request, opts ...grpc.CallOption) (*SupplyERC20Response, error)
	WithdrawERC20(ctx context.Context, in *WithdrawERC20Request, opts ...grpc.CallOption) (*WithdrawERC20Response, error)
	GetAPR(ctx context.Context, in *GetAPRRequest, opts ...grpc.CallOption) (*GetAPRResponse, error)
	GetLendingPool(ctx context.Context, in *GetLendingPoolRequest, opts ...grpc.CallOption) (*GetLendingPoolResponse, error)
	GetSuppliedBalance(ctx context.Context, in *SuppliedBalanceRequest, opts ...grpc.CallOption) (*SuppliedBalanceResponse, error)
}

type hypurrfiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHypurrfiServiceClient(cc grpc.ClientConnInterface) HypurrfiServiceClient {
	return &hypurrfiServiceClient{cc}
}

func (c *hypurrfiServiceClient) SupplyERC20(ctx context.Context, in *SupplyERC20Request, opts ...grpc.CallOption) (*SupplyERC20Response, error) {
	out := new(SupplyERC20Response)
	err := c.cc.Invoke(ctx, HypurrfiService_SupplyERC20_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypurrfiServiceClient) WithdrawERC20(ctx context.Context, in *WithdrawERC20Request, opts ...grpc.CallOption) (*WithdrawERC20Response, error) {
	out := new(WithdrawERC20Response)
	err := c.cc.Invoke(ctx, HypurrfiService_WithdrawERC20_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypurrfiServiceClient) GetAPR(ctx context.Context, in *GetAPRRequest, opts ...grpc.CallOption) (*GetAPRResponse, error) {
	out := new(GetAPRResponse)
	err := c.cc.Invoke(ctx, HypurrfiService_GetAPR_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypurrfiServiceClient) GetLendingPool(ctx context.Context, in *GetLendingPoolRequest, opts ...grpc.CallOption) (*GetLendingPoolResponse, error) {
	out := new(GetLendingPoolResponse)
	err := c.cc.Invoke(ctx, HypurrfiService_GetLendingPool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypurrfiServiceClient) GetSuppliedBalance(ctx context.Context, in *SuppliedBalanceRequest, opts ...grpc.CallOption) (*SuppliedBalanceResponse, error) {
	out := new(SuppliedBalanceResponse)
	err := c.cc.Invoke(ctx, HypurrfiService_GetSuppliedBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypurrfiServiceServer is the server API for HypurrfiService service.
// All implementations should embed UnimplementedHypurrfiServiceServer
// for forward compatibility
type HypurrfiServiceServer interface {
	SupplyERC20(context.Context, *SupplyERC20Request) (*SupplyERC20Response, error)
	WithdrawERC20(context.Context, *WithdrawERC20Request) (*WithdrawERC20Response, error)
	GetAPR(context.Context, *GetAPRRequest) (*GetAPRResponse, error)
	GetLendingPool(context.Context, *GetLendingPoolRequest) (*GetLendingPoolResponse, error)
	GetSuppliedBalance(context.Context, *SuppliedBalanceRequest) (*SuppliedBalanceResponse, error)
}

// UnimplementedHypurrfiServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHypurrfiServiceServer struct {
}

func (UnimplementedHypurrfiServiceServer) SupplyERC20(context.Context, *SupplyERC20Request) (*SupplyERC20Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyERC20 not implemented")
}
func (UnimplementedHypurrfiServiceServer) WithdrawERC20(context.Context, *WithdrawERC20Request) (*WithdrawERC20Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawERC20 not implemented")
}
func (UnimplementedHypurrfiServiceServer) GetAPR(context.Context, *GetAPRRequest) (*GetAPRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPR not implemented")
}
func (UnimplementedHypurrfiServiceServer) GetLendingPool(context.Context, *GetLendingPoolRequest) (*GetLendingPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLendingPool not implemented")
}
func (UnimplementedHypurrfiServiceServer) GetSuppliedBalance(context.Context, *SuppliedBalanceRequest) (*SuppliedBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuppliedBalance not implemented")
}

// UnsafeHypurrfiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypurrfiServiceServer will
// result in compilation errors.
type UnsafeHypurrfiServiceServer interface {
	mustEmbedUnimplementedHypurrfiServiceServer()
}

func RegisterHypurrfiServiceServer(s grpc.ServiceRegistrar, srv HypurrfiServiceServer) {
	s.RegisterService(&HypurrfiService_ServiceDesc, srv)
}

func _HypurrfiService_SupplyERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplyERC20Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypurrfiServiceServer).SupplyERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypurrfiService_SupplyERC20_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypurrfiServiceServer).SupplyERC20(ctx, req.(*SupplyERC20Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _HypurrfiService_WithdrawERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawERC20Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypurrfiServiceServer).WithdrawERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypurrfiService_WithdrawERC20_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypurrfiServiceServer).WithdrawERC20(ctx, req.(*WithdrawERC20Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _HypurrfiService_GetAPR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypurrfiServiceServer).GetAPR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypurrfiService_GetAPR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypurrfiServiceServer).GetAPR(ctx, req.(*GetAPRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HypurrfiService_GetLendingPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLendingPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypurrfiServiceServer).GetLendingPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypurrfiService_GetLendingPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypurrfiServiceServer).GetLendingPool(ctx, req.(*GetLendingPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HypurrfiService_GetSuppliedBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuppliedBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypurrfiServiceServer).GetSuppliedBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypurrfiService_GetSuppliedBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypurrfiServiceServer).GetSuppliedBalance(ctx, req.(*SuppliedBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HypurrfiService_ServiceDesc is the grpc.ServiceDesc for HypurrfiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HypurrfiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypurrfi.HypurrfiService",
	HandlerType: (*HypurrfiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupplyERC20",
			Handler:    _HypurrfiService_SupplyERC20_Handler,
		},
		{
			MethodName: "WithdrawERC20",
			Handler:    _HypurrfiService_WithdrawERC20_Handler,
		},
		{
			MethodName: "GetAPR",
			Handler:    _HypurrfiService_GetAPR_Handler,
		},
		{
			MethodName: "GetLendingPool",
			Handler:    _HypurrfiService_GetLendingPool_Handler,
		},
		{
			MethodName: "GetSuppliedBalance",
			Handler:    _HypurrfiService_GetSuppliedBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypurrfi/service.proto",
}
