// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: hyperlend/models/apy.proto

/* eslint-disable */

export const protobufPackage = "hyperlend";

export interface APYRequest {
  assetAddress: string;
}

export interface APYResponse {
  assetAddress: string;
  symbol: string;
  apr: string;
}

export const HYPERLEND_PACKAGE_NAME = "hyperlend";
