// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: hyperlend/models/getApr.proto

/* eslint-disable */

export const protobufPackage = "hyperlend";

export interface GetAPRRequest {
  tokenAddress: string;
  poolAddress: string;
}

export interface GetAPRResponse {
  supplyAPR: string;
  borrowAPR: string;
}

export const HYPERLEND_PACKAGE_NAME = "hyperlend";
