// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: hyperlend/models/getLendingPool.proto

/* eslint-disable */

export const protobufPackage = "hyperlend";

export interface GetLendingPoolRequest {
}

export interface ReserveListResponse {
  poolAddress: string;
  reserveAddress: string[];
}

export interface GetLendingPoolResponse {
  reserves: ReserveListResponse[];
}

export const HYPERLEND_PACKAGE_NAME = "hyperlend";
