// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: balance/models/balance.proto

/* eslint-disable */

export const protobufPackage = "balance";

export interface BalanceByAddressRequest {
  chainId: number;
  walletAddress: string;
  tokenAddress: string;
}

export interface BalanceResponse {
  chainId: number;
  walletAddress: string;
  tokenAddress: string;
  balance: string;
  decimals: number;
  symbol: string;
  formattedBalance: string;
  price: string;
}

export const BALANCE_PACKAGE_NAME = "balance";
