// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: biconomy/models/usePermission.proto

/* eslint-disable */

export const protobufPackage = "biconomy";

export interface UsePermissionRequest {
  orchestratorAddress: string;
  strategyId: string;
  /** contract address */
  to: string;
  /** native token value */
  value: string;
  /** transaction data */
  txData: string;
  /** chain id */
  chainId: number;
  /** fee token */
  feeToken: string;
}

export interface UsePermissionResponse {
  chainId: number;
  txHash: string;
}

export const BICONOMY_PACKAGE_NAME = "biconomy";
