// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: biconomy/models/usePermission.proto

/* eslint-disable */

export const protobufPackage = "biconomy";

export interface UsePermissionRequest {
  orchestratorAddress: string;
  strategyId: string;
  txData: Instruction[];
  feeToken: string;
  feeChainId: number;
}

export interface Call {
  to: string;
  value: string;
  data: string;
  functionSelector: string;
}

export interface Instruction {
  chainId: number;
  calls: Call[];
}

export interface UsePermissionResponse {
  chainId: number;
  txHash: string;
}

export const BICONOMY_PACKAGE_NAME = "biconomy";
