// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: protocol/models/protocol.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetInfoRequest {
  name: string;
}

export interface GetInfoResponseData {
  name: string;
  chain: string;
  token: string;
  price: number;
  tvl: number;
}

export interface GetInfoResponse {
  code: number;
  msg: string;
  data: GetInfoResponseData | undefined;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
